name: torrent_surf
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http: 0.12.2
  url_launcher: 5.5.2
  floating_search_bar: 0.3.0
  dart_standard:
    git:
      url: git://github.com/aasirmutwalli22/flutter_customs.git
      ref: loose_packages
      path: plugins/dart_standard

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true